// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWuoW7aPE-4a57UWtzs7DfUR4T8a7qxHI',
    appId: '1:708914634717:web:328920f31d9b194dee2034',
    messagingSenderId: '708914634717',
    projectId: 'sensor-monitor-f4fc5',
    authDomain: 'sensor-monitor-f4fc5.firebaseapp.com',
    storageBucket: 'sensor-monitor-f4fc5.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7OdE9IB5oD4fo-0-jMChgobF0lwRD29s',
    appId: '1:708914634717:ios:3db3f4a36fee0bb6ee2034',
    messagingSenderId: '708914634717',
    projectId: 'sensor-monitor-f4fc5',
    storageBucket: 'sensor-monitor-f4fc5.firebasestorage.app',
    iosBundleId: 'com.example.pulseMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWuoW7aPE-4a57UWtzs7DfUR4T8a7qxHI',
    appId: '1:708914634717:web:957599ba481365c6ee2034',
    messagingSenderId: '708914634717',
    projectId: 'sensor-monitor-f4fc5',
    authDomain: 'sensor-monitor-f4fc5.firebaseapp.com',
    storageBucket: 'sensor-monitor-f4fc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7OdE9IB5oD4fo-0-jMChgobF0lwRD29s',
    appId: '1:708914634717:ios:3db3f4a36fee0bb6ee2034',
    messagingSenderId: '708914634717',
    projectId: 'sensor-monitor-f4fc5',
    storageBucket: 'sensor-monitor-f4fc5.firebasestorage.app',
    iosBundleId: 'com.example.pulseMonitor',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKUscDjNeun2L9Pe_varkZEg3ZBwXJ6l0',
    appId: '1:708914634717:android:b75de18fd30a92d2ee2034',
    messagingSenderId: '708914634717',
    projectId: 'sensor-monitor-f4fc5',
    storageBucket: 'sensor-monitor-f4fc5.firebasestorage.app',
  );
}
